name: Build and push to Github packages [ghcr.io]

on:
  push:
    branches: [ "mysql8.0" ]
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      GIT_BRANCH: mysql8.0
      DOCKER_IMAGE_NAME: florinbuzec/mysql-src-h
      DOCKER_IMAGE_TAG: mysql-8.0

    steps:
      - name: Setup variables
        run: |
          echo "DOCKER_IMAGE_FULL=$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_FULL2=$DOCKER_IMAGE_NAME:mysql-8.0.33" >> $GITHUB_ENV

      - name: Safety checks
        run: |
          if [ -z "${{ secrets.GHCR_TOKEN }}" ]; then
            echo "Please configure the repository secrets with required variables (GHCR_TOKEN).";
            exit 1;
          fi;

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}
          fetch-depth: 0
        
      # - name: Lint via Hadolint tool
      #   run: |
      #     docker run --rm -i hadolint/hadolint < Dockerfile

      # not active
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/settings/tokens/new?scopes=write:packages
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.DOCKER_IMAGE_FULL }}
            ghcr.io/${{ env.DOCKER_IMAGE_FULL2 }}
