name: Build and push to Github packages [ghcr.io]

on:
  push:
    branches: [ "mariadb10.2.44" ]
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    continue-on-error: false
    env:
      GIT_BRANCH=mariadb10.2.44
      MARIADB_VERSION=10.2.44
      DOCKER_IMAGE_NAME=florinbuzec/mysql-src-h
      DOCKER_IMAGE_TAG=mariadb-10.2.44

    steps:
      - name: Setup variables
        run: |
          echo "DOCKER_IMAGE_FULL=ghcr.io/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}
          fetch-depth: 0
        
      - name: Lint via Hadolint tool
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Build Docker image
        run: |
          docker build . \
            --build-arg MARIADB_VERSION=${{ env.MARIADB_VERSION }} \
            -t ${DOCKER_IMAGE_FULL} -f ./Dockerfile .

      # https://github.com/settings/tokens/new?scopes=write:packages
      - name: Registry login
        run: |
          if [ -z "$${{ secrets.GHCR_TOKEN }}" ]; then \
            echo "Please configure the repository secrets with required variables (GHCR_TOKEN,GHCR_USERNAME)."; \
            exit 1; \
          fi; \
          echo {{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u {{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Publish image
        run: |
          docker push ${DOCKER_IMAGE_FULL}
